### ISSUE TITLE
Can't add netflow to input plugins

### ISSUE THREAD

**Issue by d-malko** [Graylog2/graylog-plugin-netflow#27]
Hello!
At first wanted to thank for your very helpful application
In new installation can't add plugin netflow.
```
plugin_dir = /usr/share/graylog-server/plugin
```
list of dir
```
[root@graylog plugin]# ls  /usr/share/graylog-server/plugin/
graylog-plugin-anonymous-usage-statistics-2.3.1.jar  graylog-plugin-map-widget-2.3.1.jar
graylog-plugin-beats-2.3.1.jar                       graylog-plugin-netflow-2.4.0-alpha.3.jar
graylog-plugin-collector-2.3.1.jar                   graylog-plugin-pipeline-processor-2.3.1.jar
graylog-plugin-enterprise-integration-2.3.1.jar      telegram-alarm-callback-1.0.0.jar
```
But after restarting graylog server there is no input Netflow UDP
Graylog version Graylog 2.3.1+9f2c6ef

**Comment by joschi** [comment]
@d-malko The NetFlow plugin 2.4.0-alpha.3 is not compatible with Graylog 2.3.x.

Please download a compatible version from https://github.com/Graylog2/graylog-plugin-netflow/releases

**Comment by d-malko** [comment]
Thank you, joshi! How could I miss that. (facepalm)
Sorry for disturbing!
