### ISSUE TITLE
graylog netflow message didn't show

### ISSUE THREAD

**Issue by 9Nick** [Graylog2/graylog-plugin-netflow#32]
I try to do follow this https://github.com/Graylog2/graylog-plugin-netflow it should success **BUT** when  click "Show received message" message didn't show (Throughput / Metrics income)
- Graylog version 2.4.5

![3](https://user-images.githubusercontent.com/40975435/42435725-9cfa1b68-8381-11e8-8eae-c2ffc170e94b.jpg)

![1](https://user-images.githubusercontent.com/40975435/42435174-f1136bca-837f-11e8-82aa-9ac2b2b7c5d1.jpg)

![2](https://user-images.githubusercontent.com/40975435/42435416-a8d79e3e-8380-11e8-996c-d5b6ab91ce59.jpg)

How to solve this issue?
Thank

**Comment by joschi** [comment]
Check the logs of your Graylog node (http://docs.graylog.org/en/2.4/pages/configuration/file_location.html) and provide a pcap of the Netflow packets arriving at the Graylog Netflow input. You can capture those with [Wireshark](https://www.wireshark.org/) or [tcpdump](https://hackertarget.com/tcpdump-examples/).

**Comment by 9Nick** [comment]
I use tcpdump form graylog server 

![4](https://user-images.githubusercontent.com/40975435/42438287-d33a4a24-8389-11e8-96bb-05b0661c451f.jpg)

**Comment by joschi** [comment]
@9Nick You need to capture the packets in a pcap and attach them to this issue. A screenshot doesn't help.

Also check the logs of your Graylog node.

**Comment by 9Nick** [comment]
I can solve this issue , because I forget input version at my router
Thank @joschi
