### ISSUE TITLE
services name

### ISSUE THREAD

**Issue by rimkov** [Graylog2/graylog-plugin-netflow#7]
Hello,
we got graylog 2.0 installed on centos7 and we added the netflow plugin, everything is fine but is it possible to "translate" port numbers as service names ? i found Protocol.java file in sources there is a way to do the same thing for services ? or maybe to parse /etc/services ?

thank you for your reply and sorry if my bad english :)

**Comment by dennisoelkers** [comment]
Thanks @rimkov for reporting this. We consider this not to be in the scope of the netflow plugin. You can probably achieve this by using the pipeline processor and/or the lookup table functionality of the core product.
