### ISSUE TITLE
Cisco ASA netflow import

### ISSUE THREAD

**Issue by truekonrads** [Graylog2/graylog-plugin-netflow#9]
Hello,

The Cisco ASA netflow doesn't seem to be parsed. I can see messages coming in via tcpdump and also the message counters get increased, but nothing appears in the list of messages when viewing the source/input.
A test using softflowd however produces the desired results.

**Comment by lennartkoopmann** [comment]
What netflow version is your ASA sending? v9?

**Comment by truekonrads** [comment]
V9/IPFIX

**Comment by lennartkoopmann** [comment]
See #6
